### ISSUE TITLE
Vue3，在 setup 中无法使用，希望可以兼容一下 Vue3 的新语法

### ISSUE THREAD

**Issue by SuperHaoHaoHao** [avil13/vue-sweetalert2#145]
版本："vue": "^3.0.0",
插件版本："vue-sweetalert2": "^5.0.2",

Vue3 中全局注入后，也没法全局使用，比如说在路由守卫里用弹窗

**Comment by avil13** [comment]
Hi.
Can I ask for a code example?
I don't understand what the error is.

**Comment by gyt95** [comment]
> Hi. Can I ask for a code example? I don't understand what the error is.

What he means is that this wrapper cannot be used in the setup syntax of Vue3. @avil13

**Comment by avil13** [comment]
@gyt95  This is because `setup` has no context

<img width="227" alt="image" src="https://user-images.githubusercontent.com/1606172/200115901-84911d99-be55-4647-b597-a1d544758203.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/1606172/200115913-44b5d3af-86b4-4882-99fb-2d18eef23455.png">

**Comment by avil13** [comment]
@SuperHaoHaoHao Если не сложно. Пишите пожалуйста по английски. Для меня он тоже не родной, но так остальные члены сообщества смогут понять о чем вы спрашиваете.
