### ISSUE TITLE
Failed to resolve entry for package "vue-sweetalert2". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by maneesha-s** [avil13/vue-sweetalert2#157]
**Describe the bug**
Please attach a link to a sandbox from [stackblitz.com](https://stackblitz.com/edit/vue-9e8haq?)  that reproduce your bug. Without the sandbox, it can be verry difficult to recreate your environment and fix the bug.
[example](https://stackblitz.com/edit/vue-9e8haq?)

**To Reproduce**
3. See error

**I also want to know**
  - Version:
  - Platform:
  - Subsystem:

**Comment by avil13** [comment]
@maneesha-s 
Your version on stackblitz.com doesn't work for some reason that is not clear right now.
The problem seems to be that the builder can't process the job.
![image](https://github.com/avil13/vue-sweetalert2/assets/1606172/25dc01fc-12c9-4ca7-8a96-fb1d359c2f87)


I have updated the version in the [example](https://github.com/avil13/vue-sweetalert2/blob/master/packages/example/) as well. Please take a look. If the problem is not fixed, you can open the issue again.
