### ISSUE TITLE
TypeError: t.forEach is not a function

### ISSUE THREAD

**Issue by jeremynikolic** [avil13/vue-sweetalert2#49]
Hi there, 

I just installed the packaged and wanted to make it use Bootstrap styling as per shown in the SweetAlert2 documentations. 
I've got this so far but get an error : 
`TypeError: t.forEach is not a function` when calling this.$swal('Hello');

Here is how I setup VueSweetAlert2:
```
import Vue from 'vue';
import VueSweetalert2 from 'vue-sweetalert2';

Vue.use(VueSweetalert2, {
    customClass: {
        confirmButton: 'btn btn-sm btn-success',
        cancelButton: 'btn btn-sm btn-danger'
    },
    buttonsStyling: false,
});

```
Any idea what I am doing wrong ?

Thanks

**Comment by jeremynikolic** [comment]
I figured it out, the interface you implemented named SweetAlertOptions requires a bit of a different syntax than the official.

So instead of the official version being:
```
{
    customClass:{
        confirmButton:'btn btn-success',
        cancelbutton:'btn btn-danger',
    },
    buttonsStyling: false,
}
```
The options need to be:
```
{
    confirmButtonClass: 'btn btn-success',
    cancelButtonClass: 'btn btn-danger',
    buttonsStyling: false,
}
```

**Comment by avil13** [comment]
I apologize for not being able to respond immediately.
With the official documentation of sweatalert - there are small discrepancies.
The version I currently use is 7, and the official library received version 8 and changed part of the API.
I have now begun work on the update, but so that users of vue-sweatalert2 did not notice anything. And the transition to the new version was unchanged.
I apologize for being so delayed. Very little free time.

**Comment by jeremynikolic** [comment]
No worries :)
