### ISSUE TITLE
What convenience does this wrapper offer?

### ISSUE THREAD

**Issue by zenflow** [avil13/vue-sweetalert2#8]
What convenience does this wrapper offer? What problem does it solve, or what does it make easier?

For the example in the README, why not just this?... Without the wrapper...

```html
<template>
    <button v-on:click="showAlert">Hello world</button>
</template>

<script>
import swal from 'sweetalert2'
export default {
    data() {
        return {};
    },
    methods: {
        showAlert(){
            // Use sweetalret2
            swal('Hello Vue world!!!');
        }
    }
}
</script>
```

I think being an integration/wrapper for sweetalert2 with Vue does not automatically mean that it is something useful.

Whatever convenience this adds, I think the description should say it, because it isn't clear.

If this package does not help significantly, then it is actually hurting, because it includes sweetalert2 as it's own dependency and so, unless a new version of this is released for every new version of the core library, (1) users will almost always be forced to use a less-than-current version of sweetalert2, and (b) users will not be able to pin their dependency at any given version of sweetalert2.

**Comment by avil13** [comment]
Good afternoon.

In fact, very valuable observations.

In my opinion, the developer of the project, in the right to do what he thinks is right.

This plugin gives a convenient wrapper over the functionality of sweetalert2.
At least, it was not just for me.

1) The possible lag in the version is the price for convenience.
2) The version of sweetalert2 is protected in the plugin version. The library is updated, the Vue plug-in is updated.

I hope I understood everything correctly.

**Comment by toverux** [comment]
> why not just this?... Without the wrapper...

Indeed, that's also what I already refused to implement a wrapper "service" in ngx-sweetalert2, because using a framework doesn't forbids you to use `import` (see https://github.com/sweetalert2/ngx-sweetalert2/issues/4). 
It also makes the dependency to SweetAlert2 more "obscure" in the sense that a static import on `sweetalert2` is more explicit.

Another future problem I see: if someday we have multiple exports in sweetalert2 (not just `default`), such a wrapper would hide that from tools like Webpack/Rollup/etc and prevent them to do tree-shaking to eliminate unused SA2 code since the library would be eagerly imported.

Imho, a new integration should provide at least one "special", framework-specific feature that makes it useful. There a are dozens of SweetAlert 1 & 2 wrappers, but very few support, for example, dynamic content in the alerts (only ngx-sweetalert2 and the pending React integration, to my knowledge) or take another approach (like ngx-sweetalert2's component and directive that I _personally_ really wanted).

Last point:

> (1) users will almost always be forced to use a less-than-current version of sweetalert2, and (b) users will not be able to pin their dependency at any given version of sweetalert2.

Yes and no. Users would be able to install and force a version of sweetalert2 that is compatible with vue-sweetalert2's version range. But this can cause various shitty issues (see https://github.com/sweetalert2/ngx-sweetalert2/issues/23, at the time sweetalert2 wasn't a peerDep) and hides the version number of sweetalert2 to the user (it won't be displayed in `npm outdated` for example).

So we should indeed change it for a peerDependency with no version restriction here (since vue-sweetalert2 does not uses sweetalert2's API... for now).

What has already been done looks ok though :) What about adding features?

**Comment by avil13** [comment]
@toverux peerDependency is a great idea, thanks. And he did.

**Comment by limonte** [comment]
> peerDependency is a great idea, thanks. And he did.

In https://github.com/sweetalert2/vue-sweetalert2/commit/613b2c1382afac0a2664be41e5d91a82e02799a5 you did it wrong. Here's the example how it should be done: https://github.com/sweetalert2/ngx-sweetalert2/blob/master/src/package.json#L8

**Comment by avil13** [comment]
Now I just did npm shrinkwrap.

And this commit [613b2c1](https://github.com/sweetalert2/vue-sweetalert2/commit/613b2c1382afac0a2664be41e5d91a82e02799a5) is not [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies).

Or am I mistaken?

**Comment by limonte** [comment]
> And this commit 613b2c1 is not peerDependencies.

The commit message is "sa2 peerDependency"

**Comment by zenflow** [comment]
@toverux Good call - the issue with the "hard" dependency on sweetalert2 can be fixed. But I still think that without a decent reason to use an additional package, it actually hurts to use an additional package (maybe in a minor way), because of the unnecessary complexity.

> It also makes the dependency to SweetAlert2 more "obscure" in the sense that a static import on sweetalert2 is more explicit

100%. Someone looking at an app's code base would have a hard time figuring out what `this.$swal` or `Vue.swal` are, whereas if the app is using `import` (like in my example above) then `swal` is lexically scoped and it's very straightforward to figure out that `swal` is the default export from the `sweetalert2` package on npm. This is the same reason as why modules are good and using the global namespace instead is not-so-good.

I didn't hear an answer from @avil13 to "What convenience does this wrapper offer?", but assuming the answer is something like "Adds the convenience of not needing to import `sweetalert2` into each file where it's used" then the single feature of this package is actually arguably hurting. It's arguable because one could argue that it's better to have 1 less line of code per file that uses sweetalert2, at the price of obscuring where the function/value comes from, but I disagree, and I think that the modern development of js modules would also disagree (see above paragraph).

**Comment by zenflow** [comment]
@avil13 Please take these criticisms as constructive and don't be discouraged from contributing to the open source community

Here's an inspiring thread I found on Twitter recently -  https://twitter.com/thejameskyle/status/949601463562526720. By the way, James Kyle is kind-of a big deal now :)

**Comment by avil13** [comment]
Thank you for the discussion.

In fact, I'm not happy anymore - I do not like talking for the sake of talking.

@zenflow, my answer was:
> In my opinion, the developer of the project, in the right to do what he thinks is right.
> This plugin gives a convenient wrapper over the functionality of sweetalert2.
> At least, it was not just for me.

In fact, the first pullrequest was to enable the user to quickly find this wrapper offer.

Personally, I prefer to use tools that work according to the rules of the framework with which you are dealing.
And I'm not alone.

Today is not my best day, so just tell me what to do.

You can return the repository back to me, because it's important to me.
Rather, better, I will do it myself if you do not mind.

In any case, thank you.

**Comment by limonte** [comment]
@avil13 after reading the discussion (which was full of valid arguments though - many thanks to @zenflow @toverux and @samturrell), I decided not to have this repository in the SweetAlert2 org.

This is all my fault, please accept my sincere apologies.

I should be more careful in future with accepting such an important contribution and give enough time to collaborators to express their opinions, which a personally value a lot.

**Actions steps:**

 - please transfer the repository back to your username
 - remove the "official" keyword from the description
 - update links in README sweetalert2/vue-sweetalert2 -> avil13/vue-sweetalert2

I appreciate your time and your will to contribute to SweetAlert2, please excuse me once again for taking your time for reverting things.

**Comment by avil13** [comment]
@limonte @zenflow @toverux 
Thanks to all.
It was interesting.
Now I think you can relax and do work)))

I wish success and all the best.
